package com.jw.domain;
// Generated Oct 14, 2010 11:31:18 PM by Hibernate Tools 3.2.4.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ContractDesign generated by hbm2java
 */
@Entity
@Table(name="contract_design"
)
public class ContractDesign  implements java.io.Serializable {


     private int id;
     private String name;
     private int maxContractors;
     private Set contracts = new HashSet(0);
     private Set contractEvents = new HashSet(0);

    public ContractDesign() {
    }

	
    public ContractDesign(int id, String name, int maxContractors) {
        this.id = id;
        this.name = name;
        this.maxContractors = maxContractors;
    }
    public ContractDesign(int id, String name, int maxContractors, Set contracts, Set contractEvents) {
       this.id = id;
       this.name = name;
       this.maxContractors = maxContractors;
       this.contracts = contracts;
       this.contractEvents = contractEvents;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="name", nullable=false, length=64)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="max_contractors", nullable=false)
    public int getMaxContractors() {
        return this.maxContractors;
    }
    
    public void setMaxContractors(int maxContractors) {
        this.maxContractors = maxContractors;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="contractDesign")
    public Set getContracts() {
        return this.contracts;
    }
    
    public void setContracts(Set contracts) {
        this.contracts = contracts;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="contractDesign")
    public Set getContractEvents() {
        return this.contractEvents;
    }
    
    public void setContractEvents(Set contractEvents) {
        this.contractEvents = contractEvents;
    }




}


