package com.jw.domain;
// Generated Oct 14, 2010 11:31:18 PM by Hibernate Tools 3.2.4.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Event generated by hbm2java
 */
@Entity
@Table(name="event"
)
public class Event  implements java.io.Serializable {


     private String name;
     private Set contractEvents = new HashSet(0);

    public Event() {
    }

	
    public Event(String name) {
        this.name = name;
    }
    public Event(String name, Set contractEvents) {
       this.name = name;
       this.contractEvents = contractEvents;
    }
   
     @Id 

    
    @Column(name="name", unique=true, nullable=false, length=64)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="event")
    public Set getContractEvents() {
        return this.contractEvents;
    }
    
    public void setContractEvents(Set contractEvents) {
        this.contractEvents = contractEvents;
    }




}


