package com.jw.domain;
// Generated Oct 14, 2010 11:31:18 PM by Hibernate Tools 3.2.4.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Passangers generated by hbm2java
 */
@Entity
@Table(name="passangers"
)
public class Passangers  implements java.io.Serializable {


     private int id;
     private Object object;
     private Player player;

    public Passangers() {
    }

    public Passangers(int id, Object object, Player player) {
       this.id = id;
       this.object = object;
       this.player = player;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="fk_object", nullable=false)
    public Object getObject() {
        return this.object;
    }
    
    public void setObject(Object object) {
        this.object = object;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="fk_player", nullable=false)
    public Player getPlayer() {
        return this.player;
    }
    
    public void setPlayer(Player player) {
        this.player = player;
    }




}


