package com.jw.domain;
// Generated Oct 14, 2010 11:31:18 PM by Hibernate Tools 3.2.4.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * TaskProp generated by hbm2java
 */
@Entity
@Table(name="task_prop"
)
public class TaskProp  implements java.io.Serializable {


     private int id;
     private Task task;
     private String name;
     private String value;
     private int priority;

    public TaskProp() {
    }

    public TaskProp(int id, Task task, String name, String value, int priority) {
       this.id = id;
       this.task = task;
       this.name = name;
       this.value = value;
       this.priority = priority;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="fk_task", nullable=false)
    public Task getTask() {
        return this.task;
    }
    
    public void setTask(Task task) {
        this.task = task;
    }

    
    @Column(name="name", nullable=false, length=64)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="value", nullable=false, length=256)
    public String getValue() {
        return this.value;
    }
    
    public void setValue(String value) {
        this.value = value;
    }

    
    @Column(name="priority", nullable=false)
    public int getPriority() {
        return this.priority;
    }
    
    public void setPriority(int priority) {
        this.priority = priority;
    }




}


