package com.jw.domain;
// Generated Oct 14, 2010 11:31:18 PM by Hibernate Tools 3.2.4.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * BuildingUsers generated by hbm2java
 */
@Entity
@Table(name="building_users"
)
public class BuildingUsers  implements java.io.Serializable {


     private int id;
     private Building building;
     private Player player;

    public BuildingUsers() {
    }

    public BuildingUsers(int id, Building building, Player player) {
       this.id = id;
       this.building = building;
       this.player = player;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="fk_building", nullable=false)
    public Building getBuilding() {
        return this.building;
    }
    
    public void setBuilding(Building building) {
        this.building = building;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="fk_player", nullable=false)
    public Player getPlayer() {
        return this.player;
    }
    
    public void setPlayer(Player player) {
        this.player = player;
    }




}


