package com.jw.domain;
// Generated Oct 14, 2010 11:31:18 PM by Hibernate Tools 3.2.4.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Building generated by hbm2java
 */
@Entity
@Table(name="building"
)
public class Building  implements java.io.Serializable {


     private int id;
     private Player player;
     private ObjectDesign objectDesign;
     private int durability;
     private Set buildingUserses = new HashSet(0);
     private Set objects = new HashSet(0);
     private Set buildingProps = new HashSet(0);

    public Building() {
    }

	
    public Building(int id, Player player, ObjectDesign objectDesign, int durability) {
        this.id = id;
        this.player = player;
        this.objectDesign = objectDesign;
        this.durability = durability;
    }
    public Building(int id, Player player, ObjectDesign objectDesign, int durability, Set buildingUserses, Set objects, Set buildingProps) {
       this.id = id;
       this.player = player;
       this.objectDesign = objectDesign;
       this.durability = durability;
       this.buildingUserses = buildingUserses;
       this.objects = objects;
       this.buildingProps = buildingProps;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="fk_owner", nullable=false)
    public Player getPlayer() {
        return this.player;
    }
    
    public void setPlayer(Player player) {
        this.player = player;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="fk_design", nullable=false)
    public ObjectDesign getObjectDesign() {
        return this.objectDesign;
    }
    
    public void setObjectDesign(ObjectDesign objectDesign) {
        this.objectDesign = objectDesign;
    }

    
    @Column(name="durability", nullable=false)
    public int getDurability() {
        return this.durability;
    }
    
    public void setDurability(int durability) {
        this.durability = durability;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="building")
    public Set getBuildingUserses() {
        return this.buildingUserses;
    }
    
    public void setBuildingUserses(Set buildingUserses) {
        this.buildingUserses = buildingUserses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="building")
    public Set getObjects() {
        return this.objects;
    }
    
    public void setObjects(Set objects) {
        this.objects = objects;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="building")
    public Set getBuildingProps() {
        return this.buildingProps;
    }
    
    public void setBuildingProps(Set buildingProps) {
        this.buildingProps = buildingProps;
    }




}


