package com.jw.domain;
// Generated Oct 14, 2010 11:31:18 PM by Hibernate Tools 3.2.4.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ContractEvent generated by hbm2java
 */
@Entity
@Table(name="contract_event"
)
public class ContractEvent  implements java.io.Serializable {


     private int id;
     private ContractDesign contractDesign;
     private Event event;

    public ContractEvent() {
    }

    public ContractEvent(int id, ContractDesign contractDesign, Event event) {
       this.id = id;
       this.contractDesign = contractDesign;
       this.event = event;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="fk_contract", nullable=false)
    public ContractDesign getContractDesign() {
        return this.contractDesign;
    }
    
    public void setContractDesign(ContractDesign contractDesign) {
        this.contractDesign = contractDesign;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="fk_event", nullable=false)
    public Event getEvent() {
        return this.event;
    }
    
    public void setEvent(Event event) {
        this.event = event;
    }




}


