package com.jw.domain;
// Generated Oct 14, 2010 11:31:18 PM by Hibernate Tools 3.2.4.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ObjectDesign generated by hbm2java
 */
@Entity
@Table(name="object_design"
)
public class ObjectDesign  implements java.io.Serializable {


     private int id;
     private int maxQuantity;
     private String name;
     private Set objects = new HashSet(0);
     private Set objectDesignProps = new HashSet(0);
     private Set recipes = new HashSet(0);
     private Set buildings = new HashSet(0);

    public ObjectDesign() {
    }

	
    public ObjectDesign(int id, int maxQuantity, String name) {
        this.id = id;
        this.maxQuantity = maxQuantity;
        this.name = name;
    }
    public ObjectDesign(int id, int maxQuantity, String name, Set objects, Set objectDesignProps, Set recipes, Set buildings) {
       this.id = id;
       this.maxQuantity = maxQuantity;
       this.name = name;
       this.objects = objects;
       this.objectDesignProps = objectDesignProps;
       this.recipes = recipes;
       this.buildings = buildings;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="max_quantity", nullable=false)
    public int getMaxQuantity() {
        return this.maxQuantity;
    }
    
    public void setMaxQuantity(int maxQuantity) {
        this.maxQuantity = maxQuantity;
    }

    
    @Column(name="name", nullable=false, length=128)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="objectDesign")
    public Set getObjects() {
        return this.objects;
    }
    
    public void setObjects(Set objects) {
        this.objects = objects;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="objectDesign")
    public Set getObjectDesignProps() {
        return this.objectDesignProps;
    }
    
    public void setObjectDesignProps(Set objectDesignProps) {
        this.objectDesignProps = objectDesignProps;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="objectDesign")
    public Set getRecipes() {
        return this.recipes;
    }
    
    public void setRecipes(Set recipes) {
        this.recipes = recipes;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="objectDesign")
    public Set getBuildings() {
        return this.buildings;
    }
    
    public void setBuildings(Set buildings) {
        this.buildings = buildings;
    }




}


