package com.jw.domain;
// Generated Oct 14, 2010 11:31:18 PM by Hibernate Tools 3.2.4.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Object generated by hbm2java
 */
@Entity
@Table(name="object"
)
public class Object  implements java.io.Serializable {


     private int id;
     private Player playerByFkUser;
     private Player playerByFkOwner;
     private ObjectDesign objectDesign;
     private Building building;
     private Object object;
     private int tile;
     private int durability;
     private int quantity;
     private float weight;
     private Set objectProps = new HashSet(0);
     private Set objects = new HashSet(0);
     private Set passangerses = new HashSet(0);

    public Object() {
    }

	
    public Object(int id, Player playerByFkOwner, ObjectDesign objectDesign, int tile, int durability, int quantity, float weight) {
        this.id = id;
        this.playerByFkOwner = playerByFkOwner;
        this.objectDesign = objectDesign;
        this.tile = tile;
        this.durability = durability;
        this.quantity = quantity;
        this.weight = weight;
    }
    public Object(int id, Player playerByFkUser, Player playerByFkOwner, ObjectDesign objectDesign, Building building, Object object, int tile, int durability, int quantity, float weight, Set objectProps, Set objects, Set passangerses) {
       this.id = id;
       this.playerByFkUser = playerByFkUser;
       this.playerByFkOwner = playerByFkOwner;
       this.objectDesign = objectDesign;
       this.building = building;
       this.object = object;
       this.tile = tile;
       this.durability = durability;
       this.quantity = quantity;
       this.weight = weight;
       this.objectProps = objectProps;
       this.objects = objects;
       this.passangerses = passangerses;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="fk_user")
    public Player getPlayerByFkUser() {
        return this.playerByFkUser;
    }
    
    public void setPlayerByFkUser(Player playerByFkUser) {
        this.playerByFkUser = playerByFkUser;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="fk_owner", nullable=false)
    public Player getPlayerByFkOwner() {
        return this.playerByFkOwner;
    }
    
    public void setPlayerByFkOwner(Player playerByFkOwner) {
        this.playerByFkOwner = playerByFkOwner;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="fk_design", nullable=false)
    public ObjectDesign getObjectDesign() {
        return this.objectDesign;
    }
    
    public void setObjectDesign(ObjectDesign objectDesign) {
        this.objectDesign = objectDesign;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="fk_container_building")
    public Building getBuilding() {
        return this.building;
    }
    
    public void setBuilding(Building building) {
        this.building = building;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="fk_container")
    public Object getObject() {
        return this.object;
    }
    
    public void setObject(Object object) {
        this.object = object;
    }

    
    @Column(name="tile", nullable=false)
    public int getTile() {
        return this.tile;
    }
    
    public void setTile(int tile) {
        this.tile = tile;
    }

    
    @Column(name="durability", nullable=false)
    public int getDurability() {
        return this.durability;
    }
    
    public void setDurability(int durability) {
        this.durability = durability;
    }

    
    @Column(name="quantity", nullable=false)
    public int getQuantity() {
        return this.quantity;
    }
    
    public void setQuantity(int quantity) {
        this.quantity = quantity;
    }

    
    @Column(name="weight", nullable=false, precision=8, scale=8)
    public float getWeight() {
        return this.weight;
    }
    
    public void setWeight(float weight) {
        this.weight = weight;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="object")
    public Set getObjectProps() {
        return this.objectProps;
    }
    
    public void setObjectProps(Set objectProps) {
        this.objectProps = objectProps;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="object")
    public Set getObjects() {
        return this.objects;
    }
    
    public void setObjects(Set objects) {
        this.objects = objects;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="object")
    public Set getPassangerses() {
        return this.passangerses;
    }
    
    public void setPassangerses(Set passangerses) {
        this.passangerses = passangerses;
    }




}


