package com.jw.domain;
// Generated Oct 14, 2010 11:31:18 PM by Hibernate Tools 3.2.4.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Recipe generated by hbm2java
 */
@Entity
@Table(name="recipe"
)
public class Recipe  implements java.io.Serializable {


     private int id;
     private Player player;
     private ObjectDesign objectDesign;

    public Recipe() {
    }

    public Recipe(int id, Player player, ObjectDesign objectDesign) {
       this.id = id;
       this.player = player;
       this.objectDesign = objectDesign;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="fk_owner", nullable=false)
    public Player getPlayer() {
        return this.player;
    }
    
    public void setPlayer(Player player) {
        this.player = player;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="fk_design", nullable=false)
    public ObjectDesign getObjectDesign() {
        return this.objectDesign;
    }
    
    public void setObjectDesign(ObjectDesign objectDesign) {
        this.objectDesign = objectDesign;
    }




}


