package com.jw.domain;
// Generated Oct 14, 2010 11:31:18 PM by Hibernate Tools 3.2.4.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Task generated by hbm2java
 */
@Entity
@Table(name="task"
)
public class Task  implements java.io.Serializable {


     private int id;
     private Contract contract;
     private Player player;
     private String action;
     private Set taskProps = new HashSet(0);

    public Task() {
    }

	
    public Task(int id, Player player, String action) {
        this.id = id;
        this.player = player;
        this.action = action;
    }
    public Task(int id, Contract contract, Player player, String action, Set taskProps) {
       this.id = id;
       this.contract = contract;
       this.player = player;
       this.action = action;
       this.taskProps = taskProps;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="fk_contract")
    public Contract getContract() {
        return this.contract;
    }
    
    public void setContract(Contract contract) {
        this.contract = contract;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="fk_player", nullable=false)
    public Player getPlayer() {
        return this.player;
    }
    
    public void setPlayer(Player player) {
        this.player = player;
    }

    
    @Column(name="action", nullable=false, length=1024)
    public String getAction() {
        return this.action;
    }
    
    public void setAction(String action) {
        this.action = action;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="task")
    public Set getTaskProps() {
        return this.taskProps;
    }
    
    public void setTaskProps(Set taskProps) {
        this.taskProps = taskProps;
    }




}


