package com.jw.domain;
// Generated Oct 14, 2010 11:31:18 PM by Hibernate Tools 3.2.4.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * War generated by hbm2java
 */
@Entity
@Table(name="war"
)
public class War  implements java.io.Serializable {


     private int id;
     private Player playerByFkAttacked;
     private Player playerByFkDeclarator;

    public War() {
    }

    public War(int id, Player playerByFkAttacked, Player playerByFkDeclarator) {
       this.id = id;
       this.playerByFkAttacked = playerByFkAttacked;
       this.playerByFkDeclarator = playerByFkDeclarator;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="fk_attacked", nullable=false)
    public Player getPlayerByFkAttacked() {
        return this.playerByFkAttacked;
    }
    
    public void setPlayerByFkAttacked(Player playerByFkAttacked) {
        this.playerByFkAttacked = playerByFkAttacked;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="fk_declarator", nullable=false)
    public Player getPlayerByFkDeclarator() {
        return this.playerByFkDeclarator;
    }
    
    public void setPlayerByFkDeclarator(Player playerByFkDeclarator) {
        this.playerByFkDeclarator = playerByFkDeclarator;
    }




}


